#!/bin/sh
#
# Automatically adds issue to to every commit message.
#

branchPath=$(git symbolic-ref -q HEAD) #Somthing like refs/heads/myBranchName
branchName=${branchPath##*/}      #Get text behind the last / of the branch path

firstLine=$(head -n1 $1)


sed -i "1s/^/$branchName: \n/" $1 #Insert branch name at the start of the commit message file

